import type { Horse } from '@/types'

// Données mockées — remplacer par un appel à l'API hippique
// ex: GET https://api.pmu.fr/rest/client/1/programme/{date}/R{n}/C{n}/participants
export const MOCK_HORSES: Horse[] = [

  // ─── Race 001 : Prix de la Marne — Trot attelé Vincennes 2100m ───────────
  {
    id: 'h-001-01', raceId: 'race-001', number: 1,
    name: 'Quador de la Brie', jockey: 'Matthieu Abrivard', trainer: 'Jean-Michel Bazire',
    owner: 'Écurie des Quatre Vents', age: 6, weight: 0,
    odds: 3.2, oddsChange: 'down',
    recentForm: [
      { position: 1, date: '2026-05-10', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 2, date: '2026-04-28', racecourse: 'Paris-Vincennes', distance: 2100, trackCondition: 'léger', raceType: 'trot', opponents: 10 },
      { position: 1, date: '2026-04-14', racecourse: 'Enghien', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 3, date: '2026-03-29', racecourse: 'Vincennes', distance: 2100, trackCondition: 'souple', raceType: 'trot', opponents: 13 },
      { position: 1, date: '2026-03-10', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'excellent', careerWins: 24, careerRaces: 48, winRate: 50.0,
    earnings: 320000, preferredDistanceMin: 2000, preferredDistanceMax: 2200,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 18, similarTrackRaces: 30,
    aiScore: 88, winProbability: 28.5, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-001-02', raceId: 'race-001', number: 2,
    name: 'Roi du Bocage', jockey: 'Éric Raffin', trainer: 'Sébastien Guarato',
    owner: 'SARL Bocage Équitation', age: 5, weight: 0,
    odds: 5.5, oddsChange: 'stable',
    recentForm: [
      { position: 2, date: '2026-05-08', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 1, date: '2026-04-22', racecourse: 'Caen', distance: 2175, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 4, date: '2026-04-06', racecourse: 'Vincennes', distance: 2100, trackCondition: 'lourd', raceType: 'trot', opponents: 12 },
      { position: 2, date: '2026-03-20', racecourse: 'Le Mans', distance: 2200, trackCondition: 'souple', raceType: 'trot', opponents: 10 },
      { position: 1, date: '2026-03-03', racecourse: 'Enghien', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
    ],
    formRating: 'bon', careerWins: 16, careerRaces: 38, winRate: 42.1,
    earnings: 190000, preferredDistanceMin: 2000, preferredDistanceMax: 2300,
    preferredConditions: ['bon'],
    similarTrackWins: 9, similarTrackRaces: 20,
    aiScore: 72, winProbability: 16.2, confidenceLevel: 'moyen', isRecommended: true,
  },
  {
    id: 'h-001-03', raceId: 'race-001', number: 3,
    name: 'Jasmine d\'Ache', jockey: 'Frank Nivard', trainer: 'Alain Provost',
    owner: 'Haras d\'Ache', age: 7, weight: 0,
    odds: 8.0, oddsChange: 'up',
    recentForm: [
      { position: 3, date: '2026-05-06', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 5, date: '2026-04-20', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 2, date: '2026-04-05', racecourse: 'Caen', distance: 2175, trackCondition: 'léger', raceType: 'trot', opponents: 10 },
      { position: 1, date: '2026-03-18', racecourse: 'Enghien', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 4, date: '2026-03-01', racecourse: 'Vincennes', distance: 2100, trackCondition: 'lourd', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'moyen', careerWins: 12, careerRaces: 55, winRate: 21.8,
    earnings: 145000, preferredDistanceMin: 2100, preferredDistanceMax: 2300,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 8, similarTrackRaces: 28,
    aiScore: 61, winProbability: 10.8, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-001-04', raceId: 'race-001', number: 4,
    name: 'Ultra Pride', jockey: 'Yoann Lebourgeois', trainer: 'Pierre Vercruysse',
    owner: 'Écurie Ultra', age: 5, weight: 0,
    odds: 12.0, oddsChange: 'stable',
    recentForm: [
      { position: 6, date: '2026-05-04', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 3, date: '2026-04-17', racecourse: 'Reims', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
      { position: 2, date: '2026-04-01', racecourse: 'Strasbourg', distance: 2175, trackCondition: 'léger', raceType: 'trot', opponents: 9 },
      { position: 5, date: '2026-03-15', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 1, date: '2026-02-28', racecourse: 'Caen', distance: 2175, trackCondition: 'souple', raceType: 'trot', opponents: 10 },
    ],
    formRating: 'moyen', careerWins: 8, careerRaces: 30, winRate: 26.7,
    earnings: 82000, preferredDistanceMin: 2000, preferredDistanceMax: 2200,
    preferredConditions: ['bon', 'léger', 'souple'],
    similarTrackWins: 4, similarTrackRaces: 15,
    aiScore: 55, winProbability: 8.1, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-001-05', raceId: 'race-001', number: 5,
    name: 'Noyal du Chêne', jockey: 'Harold Lecanu', trainer: 'Claude Provost',
    owner: 'Haras du Chêne', age: 6, weight: 0,
    odds: 15.0, oddsChange: 'up',
    recentForm: [
      { position: 4, date: '2026-05-02', racecourse: 'Le Mans', distance: 2200, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 7, date: '2026-04-15', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 3, date: '2026-03-28', racecourse: 'Caen', distance: 2175, trackCondition: 'léger', raceType: 'trot', opponents: 10 },
      { position: 2, date: '2026-03-12', racecourse: 'Bordeaux', distance: 2200, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 6, date: '2026-02-24', racecourse: 'Vincennes', distance: 2100, trackCondition: 'souple', raceType: 'trot', opponents: 13 },
    ],
    formRating: 'mauvais', careerWins: 7, careerRaces: 42, winRate: 16.7,
    earnings: 68000, preferredDistanceMin: 2100, preferredDistanceMax: 2400,
    preferredConditions: ['bon'],
    similarTrackWins: 3, similarTrackRaces: 18,
    aiScore: 44, winProbability: 5.5, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-001-06', raceId: 'race-001', number: 6,
    name: 'Galaxy Express', jockey: 'David Thomain', trainer: 'Nicolas Bazire',
    owner: 'Galaxy Racing', age: 4, weight: 0,
    odds: 18.0, oddsChange: 'stable',
    recentForm: [
      { position: 1, date: '2026-05-05', racecourse: 'Enghien', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 3, date: '2026-04-19', racecourse: 'Caen', distance: 2175, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
      { position: 2, date: '2026-04-03', racecourse: 'Reims', distance: 2100, trackCondition: 'léger', raceType: 'trot', opponents: 8 },
      { position: 5, date: '2026-03-17', racecourse: 'Strasbourg', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 1, date: '2026-02-28', racecourse: 'Bordeaux', distance: 2200, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
    ],
    formRating: 'bon', careerWins: 10, careerRaces: 22, winRate: 45.5,
    earnings: 95000, preferredDistanceMin: 2100, preferredDistanceMax: 2200,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 4, similarTrackRaces: 8,
    aiScore: 66, winProbability: 11.9, confidenceLevel: 'moyen', isRecommended: true,
  },
  {
    id: 'h-001-07', raceId: 'race-001', number: 7,
    name: 'Sultan Roc', jockey: 'Philippe Allaire', trainer: 'Olivier Allaire',
    owner: 'Écurie du Roc', age: 8, weight: 0,
    odds: 22.0, oddsChange: 'up',
    recentForm: [
      { position: 8, date: '2026-05-01', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 4, date: '2026-04-14', racecourse: 'Paris-Vincennes', distance: 2100, trackCondition: 'lourd', raceType: 'trot', opponents: 11 },
      { position: 6, date: '2026-03-27', racecourse: 'Le Mans', distance: 2200, trackCondition: 'souple', raceType: 'trot', opponents: 10 },
      { position: 3, date: '2026-03-10', racecourse: 'Caen', distance: 2175, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 9, date: '2026-02-22', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
    ],
    formRating: 'mauvais', careerWins: 15, careerRaces: 78, winRate: 19.2,
    earnings: 175000, preferredDistanceMin: 2200, preferredDistanceMax: 2500,
    preferredConditions: ['bon', 'souple'],
    similarTrackWins: 5, similarTrackRaces: 32,
    aiScore: 38, winProbability: 3.8, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-001-08', raceId: 'race-001', number: 8,
    name: 'Tempête du Nord', jockey: 'Stéphane Laval', trainer: 'Rudi Guarato',
    owner: 'Nord Racing', age: 5, weight: 0,
    odds: 9.0, oddsChange: 'down',
    recentForm: [
      { position: 2, date: '2026-05-07', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 1, date: '2026-04-21', racecourse: 'Enghien', distance: 2150, trackCondition: 'léger', raceType: 'trot', opponents: 10 },
      { position: 3, date: '2026-04-04', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 2, date: '2026-03-18', racecourse: 'Caen', distance: 2175, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 4, date: '2026-03-01', racecourse: 'Reims', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
    ],
    formRating: 'bon', careerWins: 14, careerRaces: 40, winRate: 35.0,
    earnings: 155000, preferredDistanceMin: 2000, preferredDistanceMax: 2200,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 10, similarTrackRaces: 22,
    aiScore: 75, winProbability: 14.5, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-001-09', raceId: 'race-001', number: 9,
    name: 'Nemo de Loire', jockey: 'Stefan Goop', trainer: 'Christophe Martens',
    owner: 'Loire Valley Stud', age: 6, weight: 0,
    odds: 35.0, oddsChange: 'stable',
    recentForm: [
      { position: 5, date: '2026-05-03', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 6, date: '2026-04-16', racecourse: 'Caen', distance: 2175, trackCondition: 'lourd', raceType: 'trot', opponents: 10 },
      { position: 4, date: '2026-03-30', racecourse: 'Le Mans', distance: 2200, trackCondition: 'souple', raceType: 'trot', opponents: 9 },
      { position: 7, date: '2026-03-13', racecourse: 'Bordeaux', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 5, date: '2026-02-25', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
    ],
    formRating: 'mauvais', careerWins: 5, careerRaces: 35, winRate: 14.3,
    earnings: 42000, preferredDistanceMin: 2200, preferredDistanceMax: 2600,
    preferredConditions: ['souple', 'lourd'],
    similarTrackWins: 2, similarTrackRaces: 12,
    aiScore: 32, winProbability: 2.5, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-001-10', raceId: 'race-001', number: 10,
    name: 'Prince Marcy', jockey: 'Clément Lannois', trainer: 'Dominique Belhomme',
    owner: 'Écurie Marcy', age: 5, weight: 0,
    odds: 28.0, oddsChange: 'stable',
    recentForm: [
      { position: 3, date: '2026-05-09', racecourse: 'Caen', distance: 2175, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
      { position: 4, date: '2026-04-23', racecourse: 'Enghien', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 5, date: '2026-04-07', racecourse: 'Le Mans', distance: 2200, trackCondition: 'léger', raceType: 'trot', opponents: 11 },
      { position: 2, date: '2026-03-21', racecourse: 'Reims', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 8 },
      { position: 3, date: '2026-03-05', racecourse: 'Strasbourg', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
    ],
    formRating: 'moyen', careerWins: 9, careerRaces: 38, winRate: 23.7,
    earnings: 88000, preferredDistanceMin: 2100, preferredDistanceMax: 2300,
    preferredConditions: ['bon'],
    similarTrackWins: 4, similarTrackRaces: 16,
    aiScore: 50, winProbability: 6.4, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-001-11', raceId: 'race-001', number: 11,
    name: 'Olympe d\'Elphège', jockey: 'Kévin Grégoire', trainer: 'Stéphane Ploquin',
    owner: 'Écurie Elphège', age: 7, weight: 0,
    odds: 40.0, oddsChange: 'up',
    recentForm: [
      { position: 9, date: '2026-05-01', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 8, date: '2026-04-15', racecourse: 'Caen', distance: 2175, trackCondition: 'lourd', raceType: 'trot', opponents: 10 },
      { position: 7, date: '2026-03-29', racecourse: 'Le Mans', distance: 2200, trackCondition: 'souple', raceType: 'trot', opponents: 11 },
      { position: 6, date: '2026-03-12', racecourse: 'Vincennes', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 5, date: '2026-02-24', racecourse: 'Enghien', distance: 2150, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
    ],
    formRating: 'mauvais', careerWins: 4, careerRaces: 52, winRate: 7.7,
    earnings: 28000, preferredDistanceMin: 2200, preferredDistanceMax: 2700,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 1, similarTrackRaces: 20,
    aiScore: 22, winProbability: 1.5, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-001-12', raceId: 'race-001', number: 12,
    name: 'Valmy d\'Été', jockey: 'Sylvain Mula', trainer: 'Bruno Goop',
    owner: 'Haras de Valmy', age: 4, weight: 0,
    odds: 20.0, oddsChange: 'down',
    recentForm: [
      { position: 1, date: '2026-05-11', racecourse: 'Caen', distance: 2175, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 2, date: '2026-04-25', racecourse: 'Reims', distance: 2100, trackCondition: 'bon', raceType: 'trot', opponents: 10 },
      { position: 1, date: '2026-04-09', racecourse: 'Strasbourg', distance: 2150, trackCondition: 'léger', raceType: 'trot', opponents: 8 },
      { position: 4, date: '2026-03-23', racecourse: 'Bordeaux', distance: 2200, trackCondition: 'bon', raceType: 'trot', opponents: 9 },
      { position: 3, date: '2026-03-06', racecourse: 'Le Mans', distance: 2200, trackCondition: 'souple', raceType: 'trot', opponents: 10 },
    ],
    formRating: 'excellent', careerWins: 11, careerRaces: 18, winRate: 61.1,
    earnings: 110000, preferredDistanceMin: 2000, preferredDistanceMax: 2200,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 5, similarTrackRaces: 7,
    aiScore: 70, winProbability: 10.8, confidenceLevel: 'moyen', isRecommended: false,
  },

  // ─── Race 002 : Prix du Jockey Club — Plat Chantilly 2400m ───────────────
  {
    id: 'h-002-01', raceId: 'race-002', number: 1,
    name: 'Mystère Bleu', jockey: 'Christophe Soumillon', trainer: 'André Fabre',
    owner: 'His Highness The Aga Khan', age: 3, weight: 56,
    odds: 2.8, oddsChange: 'down',
    recentForm: [
      { position: 1, date: '2026-05-05', racecourse: 'Longchamp', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-04-14', racecourse: 'Saint-Cloud', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
      { position: 2, date: '2026-03-28', racecourse: 'Chantilly', distance: 2000, trackCondition: 'léger', raceType: 'plat', opponents: 9 },
      { position: 1, date: '2026-03-08', racecourse: 'Deauville', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-02-15', racecourse: 'Cagnes-sur-Mer', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
    ],
    formRating: 'excellent', careerWins: 5, careerRaces: 6, winRate: 83.3,
    earnings: 580000, preferredDistanceMin: 1800, preferredDistanceMax: 2400,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 2, similarTrackRaces: 3,
    aiScore: 91, winProbability: 32.4, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-002-02', raceId: 'race-002', number: 2,
    name: 'Roi Soleil II', jockey: 'Frankie Dettori', trainer: 'John Gosden',
    owner: 'Godolphin', age: 3, weight: 56,
    odds: 4.2, oddsChange: 'stable',
    recentForm: [
      { position: 1, date: '2026-05-07', racecourse: 'Newmarket', distance: 2414, trackCondition: 'bon', raceType: 'plat', opponents: 10 },
      { position: 2, date: '2026-04-18', racecourse: 'Sandown', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-03-31', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 3, date: '2026-03-10', racecourse: 'Longchamp', distance: 2100, trackCondition: 'léger', raceType: 'plat', opponents: 7 },
      { position: 1, date: '2026-02-20', racecourse: 'Kempton', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 6 },
    ],
    formRating: 'excellent', careerWins: 4, careerRaces: 6, winRate: 66.7,
    earnings: 420000, preferredDistanceMin: 2000, preferredDistanceMax: 2500,
    preferredConditions: ['bon'],
    similarTrackWins: 2, similarTrackRaces: 2,
    aiScore: 83, winProbability: 22.1, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-002-03', raceId: 'race-002', number: 3,
    name: 'Tempête du Soir', jockey: 'Pierre-Charles Boudot', trainer: 'Francis-Henri Graffard',
    owner: 'Wertheimer & Frère', age: 3, weight: 56,
    odds: 6.0, oddsChange: 'down',
    recentForm: [
      { position: 2, date: '2026-05-03', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 1, date: '2026-04-16', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-03-29', racecourse: 'Saint-Cloud', distance: 2000, trackCondition: 'léger', raceType: 'plat', opponents: 7 },
      { position: 1, date: '2026-03-10', racecourse: 'Deauville', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 3, date: '2026-02-21', racecourse: 'Longchamp', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
    ],
    formRating: 'bon', careerWins: 3, careerRaces: 6, winRate: 50.0,
    earnings: 285000, preferredDistanceMin: 1800, preferredDistanceMax: 2400,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 1, similarTrackRaces: 2,
    aiScore: 77, winProbability: 17.5, confidenceLevel: 'moyen', isRecommended: true,
  },
  {
    id: 'h-002-04', raceId: 'race-002', number: 4,
    name: 'Eclipse Royale', jockey: 'Maxime Guyon', trainer: 'Carlos Laffon-Parias',
    owner: 'Khalid Abdulla', age: 3, weight: 56,
    odds: 9.0, oddsChange: 'stable',
    recentForm: [
      { position: 3, date: '2026-05-01', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-04-14', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 4, date: '2026-03-27', racecourse: 'Saint-Cloud', distance: 2000, trackCondition: 'léger', raceType: 'plat', opponents: 7 },
      { position: 1, date: '2026-03-07', racecourse: 'Chantilly', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-02-18', racecourse: 'Cagnes-sur-Mer', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
    ],
    formRating: 'bon', careerWins: 2, careerRaces: 6, winRate: 33.3,
    earnings: 180000, preferredDistanceMin: 1800, preferredDistanceMax: 2200,
    preferredConditions: ['bon'],
    similarTrackWins: 1, similarTrackRaces: 3,
    aiScore: 65, winProbability: 11.4, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-002-05', raceId: 'race-002', number: 5,
    name: 'Diamant Noir', jockey: 'Olivier Peslier', trainer: 'Mikel Delzangles',
    owner: 'Écurie Pantall', age: 3, weight: 56,
    odds: 14.0, oddsChange: 'up',
    recentForm: [
      { position: 4, date: '2026-04-30', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 3, date: '2026-04-13', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 5, date: '2026-03-25', racecourse: 'Saint-Cloud', distance: 2100, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 2, date: '2026-03-05', racecourse: 'Deauville', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-02-16', racecourse: 'Cagnes-sur-Mer', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
    ],
    formRating: 'moyen', careerWins: 2, careerRaces: 7, winRate: 28.6,
    earnings: 120000, preferredDistanceMin: 1800, preferredDistanceMax: 2200,
    preferredConditions: ['bon', 'souple'],
    similarTrackWins: 0, similarTrackRaces: 2,
    aiScore: 52, winProbability: 7.3, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-002-06', raceId: 'race-002', number: 6,
    name: 'Éclat d\'Or', jockey: 'Stéphane Pasquier', trainer: 'Robert Collet',
    owner: 'Marquise de Moratalla', age: 3, weight: 56,
    odds: 20.0, oddsChange: 'stable',
    recentForm: [
      { position: 5, date: '2026-04-28', racecourse: 'Chantilly', distance: 2400, trackCondition: 'bon', raceType: 'plat', opponents: 10 },
      { position: 4, date: '2026-04-10', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 3, date: '2026-03-22', racecourse: 'Saint-Cloud', distance: 2000, trackCondition: 'léger', raceType: 'plat', opponents: 8 },
      { position: 6, date: '2026-03-03', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 2, date: '2026-02-12', racecourse: 'Cagnes-sur-Mer', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'moyen', careerWins: 1, careerRaces: 7, winRate: 14.3,
    earnings: 75000, preferredDistanceMin: 2000, preferredDistanceMax: 2600,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 0, similarTrackRaces: 2,
    aiScore: 42, winProbability: 4.2, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-002-07', raceId: 'race-002', number: 7,
    name: 'Prince Azur', jockey: 'Mickaël Barzalona', trainer: 'Alain de Royer-Dupré',
    owner: 'His Highness The Aga Khan', age: 3, weight: 56,
    odds: 12.0, oddsChange: 'down',
    recentForm: [
      { position: 2, date: '2026-05-02', racecourse: 'Chantilly', distance: 2400, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 3, date: '2026-04-16', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-03-30', racecourse: 'Saint-Cloud', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
      { position: 4, date: '2026-03-12', racecourse: 'Deauville', distance: 2000, trackCondition: 'léger', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-02-22', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
    ],
    formRating: 'bon', careerWins: 2, careerRaces: 6, winRate: 33.3,
    earnings: 148000, preferredDistanceMin: 2000, preferredDistanceMax: 2600,
    preferredConditions: ['bon'],
    similarTrackWins: 1, similarTrackRaces: 2,
    aiScore: 68, winProbability: 12.4, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-002-08', raceId: 'race-002', number: 8,
    name: 'Vent du Large', jockey: 'Thierry Jarnet', trainer: 'Jean-Claude Rouget',
    owner: 'Écurie Barande-Barbe', age: 3, weight: 56,
    odds: 30.0, oddsChange: 'up',
    recentForm: [
      { position: 6, date: '2026-04-29', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 5, date: '2026-04-12', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 10 },
      { position: 4, date: '2026-03-24', racecourse: 'Saint-Cloud', distance: 2000, trackCondition: 'léger', raceType: 'plat', opponents: 8 },
      { position: 3, date: '2026-03-04', racecourse: 'Deauville', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
      { position: 7, date: '2026-02-14', racecourse: 'Cagnes-sur-Mer', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'mauvais', careerWins: 1, careerRaces: 8, winRate: 12.5,
    earnings: 48000, preferredDistanceMin: 1800, preferredDistanceMax: 2200,
    preferredConditions: ['bon'],
    similarTrackWins: 0, similarTrackRaces: 2,
    aiScore: 28, winProbability: 2.2, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-002-09', raceId: 'race-002', number: 9,
    name: 'Liberté d\'Or', jockey: 'Alexis Badel', trainer: 'Didier Guillemin',
    owner: 'Écurie Freedman', age: 3, weight: 56,
    odds: 18.0, oddsChange: 'stable',
    recentForm: [
      { position: 3, date: '2026-04-27', racecourse: 'Chantilly', distance: 2400, trackCondition: 'bon', raceType: 'plat', opponents: 10 },
      { position: 4, date: '2026-04-09', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 2, date: '2026-03-23', racecourse: 'Saint-Cloud', distance: 2000, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 5, date: '2026-03-01', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 3, date: '2026-02-10', racecourse: 'Cagnes-sur-Mer', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'moyen', careerWins: 1, careerRaces: 6, winRate: 16.7,
    earnings: 90000, preferredDistanceMin: 2000, preferredDistanceMax: 2500,
    preferredConditions: ['bon', 'souple'],
    similarTrackWins: 0, similarTrackRaces: 2,
    aiScore: 48, winProbability: 5.4, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-002-10', raceId: 'race-002', number: 10,
    name: 'Coeur Vaillant', jockey: 'Tony Piccone', trainer: 'Pascal Bary',
    owner: 'Écurie Volterra', age: 3, weight: 56,
    odds: 25.0, oddsChange: 'up',
    recentForm: [
      { position: 7, date: '2026-04-25', racecourse: 'Longchamp', distance: 2100, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 6, date: '2026-04-07', racecourse: 'Chantilly', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 10 },
      { position: 5, date: '2026-03-20', racecourse: 'Saint-Cloud', distance: 2100, trackCondition: 'léger', raceType: 'plat', opponents: 8 },
      { position: 4, date: '2026-02-28', racecourse: 'Deauville', distance: 2000, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
      { position: 6, date: '2026-02-08', racecourse: 'Cagnes-sur-Mer', distance: 1800, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
    ],
    formRating: 'mauvais', careerWins: 0, careerRaces: 7, winRate: 0,
    earnings: 22000, preferredDistanceMin: 1800, preferredDistanceMax: 2200,
    preferredConditions: ['bon'],
    similarTrackWins: 0, similarTrackRaces: 2,
    aiScore: 20, winProbability: 1.5, confidenceLevel: 'faible', isRecommended: false,
  },

  // ─── Race 003 : Grand Prix de Paris — Plat Longchamp 1600m ──────────────
  {
    id: 'h-003-01', raceId: 'race-003', number: 1,
    name: 'Lumière d\'Aube', jockey: 'Pierre-Charles Boudot', trainer: 'Francis-Henri Graffard',
    owner: 'Gestut Fahrhof', age: 4, weight: 58,
    odds: 3.5, oddsChange: 'down',
    recentForm: [
      { position: 1, date: '2026-05-04', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 1, date: '2026-04-18', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-03-31', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 1, date: '2026-03-11', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 3, date: '2026-02-21', racecourse: 'Deauville', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'excellent', careerWins: 8, careerRaces: 14, winRate: 57.1,
    earnings: 380000, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
    preferredConditions: ['souple', 'bon'],
    similarTrackWins: 6, similarTrackRaces: 8,
    aiScore: 87, winProbability: 29.8, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-003-02', raceId: 'race-003', number: 2,
    name: 'Étoile Filante', jockey: 'Christophe Soumillon', trainer: 'André Fabre',
    owner: 'His Highness The Aga Khan', age: 4, weight: 56,
    odds: 5.0, oddsChange: 'stable',
    recentForm: [
      { position: 2, date: '2026-05-06', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-04-20', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 3, date: '2026-04-02', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 2, date: '2026-03-15', racecourse: 'Longchamp', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-02-25', racecourse: 'Cagnes-sur-Mer', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
    ],
    formRating: 'bon', careerWins: 6, careerRaces: 12, winRate: 50.0,
    earnings: 260000, preferredDistanceMin: 1400, preferredDistanceMax: 2000,
    preferredConditions: ['bon', 'souple'],
    similarTrackWins: 3, similarTrackRaces: 5,
    aiScore: 79, winProbability: 22.6, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-003-03', raceId: 'race-003', number: 3,
    name: 'Alizé Royal', jockey: 'Maxime Guyon', trainer: 'Carlos Laffon-Parias',
    owner: 'Khalid Abdulla', age: 5, weight: 59,
    odds: 7.0, oddsChange: 'up',
    recentForm: [
      { position: 3, date: '2026-05-02', racecourse: 'Longchamp', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-04-16', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 4, date: '2026-03-29', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 1, date: '2026-03-08', racecourse: 'Deauville', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-02-18', racecourse: 'Longchamp', distance: 1600, trackCondition: 'léger', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'bon', careerWins: 7, careerRaces: 18, winRate: 38.9,
    earnings: 195000, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
    preferredConditions: ['bon'],
    similarTrackWins: 2, similarTrackRaces: 6,
    aiScore: 66, winProbability: 15.2, confidenceLevel: 'moyen', isRecommended: true,
  },
  {
    id: 'h-003-04', raceId: 'race-003', number: 4,
    name: 'Ouragan du Cap', jockey: 'Olivier Peslier', trainer: 'Mikel Delzangles',
    owner: 'Écurie Pantall', age: 4, weight: 57,
    odds: 11.0, oddsChange: 'stable',
    recentForm: [
      { position: 4, date: '2026-04-30', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 5, date: '2026-04-13', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 2, date: '2026-03-26', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 3, date: '2026-03-06', racecourse: 'Longchamp', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 1, date: '2026-02-14', racecourse: 'Cagnes-sur-Mer', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
    ],
    formRating: 'moyen', careerWins: 4, careerRaces: 14, winRate: 28.6,
    earnings: 115000, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
    preferredConditions: ['souple', 'bon'],
    similarTrackWins: 2, similarTrackRaces: 5,
    aiScore: 59, winProbability: 10.8, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-003-05', raceId: 'race-003', number: 5,
    name: 'Mistral d\'Été', jockey: 'Stéphane Pasquier', trainer: 'Robert Collet',
    owner: 'Écurie Moratalla', age: 5, weight: 60,
    odds: 16.0, oddsChange: 'up',
    recentForm: [
      { position: 6, date: '2026-04-28', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 4, date: '2026-04-11', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 3, date: '2026-03-24', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 5, date: '2026-03-03', racecourse: 'Deauville', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 4, date: '2026-02-11', racecourse: 'Longchamp', distance: 1600, trackCondition: 'léger', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'mauvais', careerWins: 3, careerRaces: 16, winRate: 18.8,
    earnings: 72000, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
    preferredConditions: ['souple'],
    similarTrackWins: 2, similarTrackRaces: 7,
    aiScore: 44, winProbability: 6.1, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-003-06', raceId: 'race-003', number: 6,
    name: 'Zéphyr Bleu', jockey: 'Alexis Badel', trainer: 'Didier Guillemin',
    owner: 'Écurie Freedman', age: 4, weight: 57,
    odds: 22.0, oddsChange: 'stable',
    recentForm: [
      { position: 5, date: '2026-04-26', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 6, date: '2026-04-08', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 5, date: '2026-03-21', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 7 },
      { position: 4, date: '2026-02-28', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 7, date: '2026-02-08', racecourse: 'Cagnes-sur-Mer', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'mauvais', careerWins: 2, careerRaces: 12, winRate: 16.7,
    earnings: 55000, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
    preferredConditions: ['bon'],
    similarTrackWins: 1, similarTrackRaces: 5,
    aiScore: 35, winProbability: 3.8, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-003-07', raceId: 'race-003', number: 7,
    name: 'Tonnerre de Zeus', jockey: 'Tony Piccone', trainer: 'Pascal Bary',
    owner: 'Écurie Volterra', age: 6, weight: 61,
    odds: 35.0, oddsChange: 'up',
    recentForm: [
      { position: 7, date: '2026-04-24', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 8, date: '2026-04-06', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 6, date: '2026-03-19', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 7, date: '2026-02-26', racecourse: 'Deauville', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 8 },
      { position: 5, date: '2026-02-06', racecourse: 'Longchamp', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
    ],
    formRating: 'mauvais', careerWins: 1, careerRaces: 18, winRate: 5.6,
    earnings: 20000, preferredDistanceMin: 1600, preferredDistanceMax: 2000,
    preferredConditions: ['bon'],
    similarTrackWins: 0, similarTrackRaces: 6,
    aiScore: 18, winProbability: 1.8, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-003-08', raceId: 'race-003', number: 8,
    name: 'Saphir d\'Argent', jockey: 'Mickaël Barzalona', trainer: 'Alain de Royer-Dupré',
    owner: 'His Highness The Aga Khan', age: 4, weight: 56,
    odds: 8.0, oddsChange: 'down',
    recentForm: [
      { position: 2, date: '2026-05-03', racecourse: 'Chantilly', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 3, date: '2026-04-17', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 7 },
      { position: 1, date: '2026-03-31', racecourse: 'Saint-Cloud', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
      { position: 2, date: '2026-03-13', racecourse: 'Chantilly', distance: 1600, trackCondition: 'bon', raceType: 'plat', opponents: 9 },
      { position: 4, date: '2026-02-23', racecourse: 'Longchamp', distance: 1600, trackCondition: 'souple', raceType: 'plat', opponents: 8 },
    ],
    formRating: 'bon', careerWins: 5, careerRaces: 11, winRate: 45.5,
    earnings: 165000, preferredDistanceMin: 1400, preferredDistanceMax: 1800,
    preferredConditions: ['souple'],
    similarTrackWins: 3, similarTrackRaces: 5,
    aiScore: 74, winProbability: 17.8, confidenceLevel: 'moyen', isRecommended: false,
  },

  // ─── Race 004 : Prix du Président — Obstacle Auteuil 3200m ───────────────
  {
    id: 'h-004-01', raceId: 'race-004', number: 1,
    name: 'Vaillant Mousquetaire', jockey: 'Barry Geraghty', trainer: 'Guillaume Macaire',
    owner: 'Écurie des Mousquetaires', age: 7, weight: 72,
    odds: 4.0, oddsChange: 'down',
    recentForm: [
      { position: 1, date: '2026-05-04', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 2, date: '2026-04-18', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 1, date: '2026-03-30', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
      { position: 3, date: '2026-03-10', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 1, date: '2026-02-20', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'excellent', careerWins: 12, careerRaces: 28, winRate: 42.9,
    earnings: 280000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['lourd', 'très lourd'],
    similarTrackWins: 8, similarTrackRaces: 15,
    aiScore: 85, winProbability: 27.2, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-004-02', raceId: 'race-004', number: 2,
    name: 'Éclair de Lune', jockey: 'Davy Russell', trainer: 'François Nicolle',
    owner: 'Écurie de Lune', age: 8, weight: 73,
    odds: 5.5, oddsChange: 'stable',
    recentForm: [
      { position: 2, date: '2026-05-02', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 1, date: '2026-04-15', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 3, date: '2026-03-28', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
      { position: 1, date: '2026-03-08', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 2, date: '2026-02-18', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'bon', careerWins: 10, careerRaces: 30, winRate: 33.3,
    earnings: 195000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['lourd'],
    similarTrackWins: 6, similarTrackRaces: 14,
    aiScore: 78, winProbability: 21.5, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-004-03', raceId: 'race-004', number: 3,
    name: 'Tonnerre Royal', jockey: 'Noel Fehily', trainer: 'Thierry Doumen',
    owner: 'Royal Racing', age: 6, weight: 71,
    odds: 7.0, oddsChange: 'down',
    recentForm: [
      { position: 3, date: '2026-04-30', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 2, date: '2026-04-13', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 1, date: '2026-03-26', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
      { position: 4, date: '2026-03-05', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 2, date: '2026-02-14', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'bon', careerWins: 8, careerRaces: 22, winRate: 36.4,
    earnings: 148000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['lourd', 'très lourd'],
    similarTrackWins: 5, similarTrackRaces: 10,
    aiScore: 71, winProbability: 17.8, confidenceLevel: 'moyen', isRecommended: true,
  },
  {
    id: 'h-004-04', raceId: 'race-004', number: 4,
    name: 'Duc de Saumur', jockey: 'Ruby Walsh', trainer: 'Emmanuel Clayeux',
    owner: 'Écurie de Saumur', age: 9, weight: 74,
    odds: 12.0, oddsChange: 'up',
    recentForm: [
      { position: 5, date: '2026-04-28', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 4, date: '2026-04-10', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 2, date: '2026-03-24', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
      { position: 6, date: '2026-03-03', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 3, date: '2026-02-12', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'moyen', careerWins: 9, careerRaces: 40, winRate: 22.5,
    earnings: 165000, preferredDistanceMin: 3000, preferredDistanceMax: 4500,
    preferredConditions: ['très lourd'],
    similarTrackWins: 3, similarTrackRaces: 16,
    aiScore: 56, winProbability: 11.2, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-004-05', raceId: 'race-004', number: 5,
    name: 'Feu d\'Artifice', jockey: 'Bertrand Lestrade', trainer: 'Patrice Quinton',
    owner: 'SAS Quinton Racing', age: 7, weight: 70,
    odds: 20.0, oddsChange: 'stable',
    recentForm: [
      { position: 6, date: '2026-04-26', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 5, date: '2026-04-08', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 4, date: '2026-03-22', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
      { position: 3, date: '2026-03-01', racecourse: 'Compiegne', distance: 3000, trackCondition: 'bon', raceType: 'obstacle', opponents: 9 },
      { position: 7, date: '2026-02-10', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'mauvais', careerWins: 4, careerRaces: 25, winRate: 16.0,
    earnings: 62000, preferredDistanceMin: 2800, preferredDistanceMax: 3500,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 1, similarTrackRaces: 10,
    aiScore: 40, winProbability: 6.4, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-004-06', raceId: 'race-004', number: 6,
    name: 'Cap Vert', jockey: 'Johnny Charron', trainer: 'Gérald Cherel',
    owner: 'Écurie Cherel', age: 6, weight: 71,
    odds: 30.0, oddsChange: 'up',
    recentForm: [
      { position: 7, date: '2026-04-24', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 8, date: '2026-04-06', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 6, date: '2026-03-19', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
      { position: 5, date: '2026-02-27', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 8, date: '2026-02-07', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'mauvais', careerWins: 2, careerRaces: 22, winRate: 9.1,
    earnings: 28000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['bon'],
    similarTrackWins: 0, similarTrackRaces: 8,
    aiScore: 22, winProbability: 2.8, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-004-07', raceId: 'race-004', number: 7,
    name: 'Esprit du Vent', jockey: 'Amaury Dumont', trainer: 'Yannick Fouin',
    owner: 'Haras du Vent', age: 5, weight: 69,
    odds: 15.0, oddsChange: 'stable',
    recentForm: [
      { position: 4, date: '2026-04-22', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 3, date: '2026-04-04', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 5, date: '2026-03-17', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
      { position: 2, date: '2026-02-25', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 4, date: '2026-02-05', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'moyen', careerWins: 3, careerRaces: 14, winRate: 21.4,
    earnings: 58000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['lourd'],
    similarTrackWins: 2, similarTrackRaces: 6,
    aiScore: 51, winProbability: 8.1, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-004-08', raceId: 'race-004', number: 8,
    name: 'Guerrier d\'Acier', jockey: 'Maxime Monfort', trainer: 'Yves Durepaire',
    owner: 'Écurie Acier', age: 8, weight: 73,
    odds: 25.0, oddsChange: 'down',
    recentForm: [
      { position: 3, date: '2026-04-20', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 6, date: '2026-04-02', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 7, date: '2026-03-15', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
      { position: 4, date: '2026-02-23', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 5, date: '2026-02-03', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'mauvais', careerWins: 5, careerRaces: 35, winRate: 14.3,
    earnings: 90000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['lourd'],
    similarTrackWins: 2, similarTrackRaces: 14,
    aiScore: 35, winProbability: 4.5, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-004-09', raceId: 'race-004', number: 9,
    name: 'Horizon Doré', jockey: 'Liam Treadwell', trainer: 'Henri de Nicolay',
    owner: 'Haras d\'Horizon', age: 7, weight: 72,
    odds: 40.0, oddsChange: 'up',
    recentForm: [
      { position: 8, date: '2026-04-18', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 7, date: '2026-03-31', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 8, date: '2026-03-13', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
      { position: 7, date: '2026-02-21', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 6, date: '2026-02-01', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'mauvais', careerWins: 1, careerRaces: 28, winRate: 3.6,
    earnings: 18000, preferredDistanceMin: 3000, preferredDistanceMax: 4000,
    preferredConditions: ['lourd'],
    similarTrackWins: 0, similarTrackRaces: 12,
    aiScore: 15, winProbability: 1.5, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-004-10', raceId: 'race-004', number: 10,
    name: 'Tempête de Fer', jockey: 'Sébastien Meunier', trainer: 'Christophe Ferland',
    owner: 'Écurie Ferland', age: 6, weight: 70,
    odds: 18.0, oddsChange: 'down',
    recentForm: [
      { position: 4, date: '2026-04-16', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 9 },
      { position: 5, date: '2026-03-29', racecourse: 'Enghien', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 3, date: '2026-03-11', racecourse: 'Auteuil', distance: 3200, trackCondition: 'lourd', raceType: 'obstacle', opponents: 10 },
      { position: 1, date: '2026-02-19', racecourse: 'Compiegne', distance: 3000, trackCondition: 'lourd', raceType: 'obstacle', opponents: 8 },
      { position: 4, date: '2026-01-30', racecourse: 'Auteuil', distance: 3200, trackCondition: 'très lourd', raceType: 'obstacle', opponents: 10 },
    ],
    formRating: 'moyen', careerWins: 4, careerRaces: 18, winRate: 22.2,
    earnings: 72000, preferredDistanceMin: 3000, preferredDistanceMax: 3500,
    preferredConditions: ['lourd'],
    similarTrackWins: 3, similarTrackRaces: 8,
    aiScore: 58, winProbability: 9.3, confidenceLevel: 'moyen', isRecommended: false,
  },

  // ─── Race 005 : Quinté+ du Soir — Trot attelé Vincennes 2700m ────────────
  {
    id: 'h-005-01', raceId: 'race-005', number: 1,
    name: 'Idéal du Gazeau', jockey: 'Jean-Michel Bazire', trainer: 'Jean-Michel Bazire',
    owner: 'Bazire Racing', age: 8, weight: 0,
    odds: 4.5, oddsChange: 'down',
    recentForm: [
      { position: 1, date: '2026-05-08', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 2, date: '2026-04-24', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 1, date: '2026-04-08', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 3, date: '2026-03-22', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 1, date: '2026-03-05', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
    ],
    formRating: 'excellent', careerWins: 32, careerRaces: 62, winRate: 51.6,
    earnings: 850000, preferredDistanceMin: 2500, preferredDistanceMax: 2800,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 22, similarTrackRaces: 38,
    aiScore: 90, winProbability: 24.8, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-005-02', raceId: 'race-005', number: 2,
    name: 'Face Time Bourbon', jockey: 'Matthieu Abrivard', trainer: 'Philippe Allaire',
    owner: 'Écurie Allaire', age: 9, weight: 0,
    odds: 6.0, oddsChange: 'stable',
    recentForm: [
      { position: 2, date: '2026-05-06', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 1, date: '2026-04-20', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 3, date: '2026-04-04', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 1, date: '2026-03-18', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 2, date: '2026-03-01', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
    ],
    formRating: 'excellent', careerWins: 28, careerRaces: 55, winRate: 50.9,
    earnings: 720000, preferredDistanceMin: 2500, preferredDistanceMax: 3000,
    preferredConditions: ['bon'],
    similarTrackWins: 18, similarTrackRaces: 32,
    aiScore: 84, winProbability: 19.6, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-005-03', raceId: 'race-005', number: 3,
    name: 'Bold Eagle Junior', jockey: 'Éric Raffin', trainer: 'Sébastien Guarato',
    owner: 'SARL Bold Racing', age: 7, weight: 0,
    odds: 8.0, oddsChange: 'down',
    recentForm: [
      { position: 3, date: '2026-05-04', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 2, date: '2026-04-17', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 1, date: '2026-04-01', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 4, date: '2026-03-15', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 2, date: '2026-02-27', racecourse: 'Le Mans', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'bon', careerWins: 20, careerRaces: 48, winRate: 41.7,
    earnings: 490000, preferredDistanceMin: 2500, preferredDistanceMax: 2800,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 12, similarTrackRaces: 28,
    aiScore: 78, winProbability: 16.2, confidenceLevel: 'fort', isRecommended: true,
  },
  {
    id: 'h-005-04', raceId: 'race-005', number: 4,
    name: 'Rock du Guéret', jockey: 'Frank Nivard', trainer: 'Alain Provost',
    owner: 'Haras du Guéret', age: 6, weight: 0,
    odds: 10.0, oddsChange: 'stable',
    recentForm: [
      { position: 4, date: '2026-05-02', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 5, date: '2026-04-15', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 2, date: '2026-03-29', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 3, date: '2026-03-12', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 6, date: '2026-02-24', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
    ],
    formRating: 'moyen', careerWins: 15, careerRaces: 45, winRate: 33.3,
    earnings: 285000, preferredDistanceMin: 2600, preferredDistanceMax: 3000,
    preferredConditions: ['bon'],
    similarTrackWins: 8, similarTrackRaces: 22,
    aiScore: 65, winProbability: 11.4, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-005-05', raceId: 'race-005', number: 5,
    name: 'Readly Express II', jockey: 'Björn Goop', trainer: 'Daniel Redén',
    owner: 'Stall Goop', age: 8, weight: 0,
    odds: 12.0, oddsChange: 'up',
    recentForm: [
      { position: 6, date: '2026-04-30', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 3, date: '2026-04-13', racecourse: 'Romme', distance: 2640, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 2, date: '2026-03-27', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 5, date: '2026-03-09', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 13 },
      { position: 1, date: '2026-02-22', racecourse: 'Solvalla', distance: 2640, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
    ],
    formRating: 'moyen', careerWins: 22, careerRaces: 58, winRate: 37.9,
    earnings: 580000, preferredDistanceMin: 2500, preferredDistanceMax: 3000,
    preferredConditions: ['bon'],
    similarTrackWins: 8, similarTrackRaces: 24,
    aiScore: 62, winProbability: 9.8, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-005-06', raceId: 'race-005', number: 6,
    name: 'Zacon Gio', jockey: 'Yoann Lebourgeois', trainer: 'Pierre Vercruysse',
    owner: 'Écurie Ultra', age: 7, weight: 0,
    odds: 15.0, oddsChange: 'stable',
    recentForm: [
      { position: 5, date: '2026-04-28', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 4, date: '2026-04-11', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 3, date: '2026-03-25', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 6, date: '2026-03-07', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 4, date: '2026-02-19', racecourse: 'Le Mans', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'moyen', careerWins: 12, careerRaces: 42, winRate: 28.6,
    earnings: 198000, preferredDistanceMin: 2600, preferredDistanceMax: 3200,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 6, similarTrackRaces: 18,
    aiScore: 55, winProbability: 7.6, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-005-07', raceId: 'race-005', number: 7,
    name: 'Vivid Wise As', jockey: 'Harold Lecanu', trainer: 'Claude Provost',
    owner: 'Haras du Chêne', age: 6, weight: 0,
    odds: 20.0, oddsChange: 'down',
    recentForm: [
      { position: 7, date: '2026-04-26', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 6, date: '2026-04-09', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 4, date: '2026-03-23', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 2, date: '2026-03-05', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 5, date: '2026-02-17', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
    ],
    formRating: 'mauvais', careerWins: 10, careerRaces: 35, winRate: 28.6,
    earnings: 165000, preferredDistanceMin: 2500, preferredDistanceMax: 2800,
    preferredConditions: ['bon'],
    similarTrackWins: 5, similarTrackRaces: 16,
    aiScore: 46, winProbability: 5.4, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-005-08', raceId: 'race-005', number: 8,
    name: 'Propulsion', jockey: 'Björn Goop', trainer: 'Sébastien Guarato',
    owner: 'Haras de Corta', age: 8, weight: 0,
    odds: 18.0, oddsChange: 'stable',
    recentForm: [
      { position: 3, date: '2026-04-24', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 7, date: '2026-04-07', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 5, date: '2026-03-21', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 4, date: '2026-03-03', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 3, date: '2026-02-15', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
    ],
    formRating: 'moyen', careerWins: 18, careerRaces: 52, winRate: 34.6,
    earnings: 440000, preferredDistanceMin: 2500, preferredDistanceMax: 3000,
    preferredConditions: ['bon'],
    similarTrackWins: 10, similarTrackRaces: 26,
    aiScore: 58, winProbability: 8.5, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-005-09', raceId: 'race-005', number: 9,
    name: 'Ringostarr Treb', jockey: 'Stefan Goop', trainer: 'Sébastien Guarato',
    owner: 'Stall Guarato', age: 6, weight: 0,
    odds: 22.0, oddsChange: 'up',
    recentForm: [
      { position: 8, date: '2026-04-22', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 5, date: '2026-04-05', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 6, date: '2026-03-19', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 3, date: '2026-03-01', racecourse: 'Caen', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 11 },
      { position: 7, date: '2026-02-13', racecourse: 'Le Mans', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'mauvais', careerWins: 9, careerRaces: 38, winRate: 23.7,
    earnings: 148000, preferredDistanceMin: 2600, preferredDistanceMax: 3000,
    preferredConditions: ['bon'],
    similarTrackWins: 4, similarTrackRaces: 16,
    aiScore: 38, winProbability: 3.8, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-005-10', raceId: 'race-005', number: 10,
    name: 'Aetos Kronos', jockey: 'Kévin Grégoire', trainer: 'Stéphane Ploquin',
    owner: 'Écurie Kronos', age: 7, weight: 0,
    odds: 28.0, oddsChange: 'stable',
    recentForm: [
      { position: 9, date: '2026-04-20', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 8, date: '2026-04-03', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 7, date: '2026-03-17', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 5, date: '2026-02-27', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 6, date: '2026-02-10', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
    ],
    formRating: 'mauvais', careerWins: 6, careerRaces: 40, winRate: 15.0,
    earnings: 92000, preferredDistanceMin: 2700, preferredDistanceMax: 3200,
    preferredConditions: ['bon'],
    similarTrackWins: 3, similarTrackRaces: 18,
    aiScore: 28, winProbability: 2.5, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-005-11', raceId: 'race-005', number: 11,
    name: 'Looking Superb', jockey: 'David Thomain', trainer: 'Nicolas Bazire',
    owner: 'Galaxy Racing', age: 5, weight: 0,
    odds: 35.0, oddsChange: 'up',
    recentForm: [
      { position: 10, date: '2026-04-18', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 9, date: '2026-04-01', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 8, date: '2026-03-15', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 6, date: '2026-02-25', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 9, date: '2026-02-08', racecourse: 'Le Mans', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'mauvais', careerWins: 3, careerRaces: 22, winRate: 13.6,
    earnings: 42000, preferredDistanceMin: 2500, preferredDistanceMax: 2800,
    preferredConditions: ['bon'],
    similarTrackWins: 1, similarTrackRaces: 8,
    aiScore: 18, winProbability: 1.2, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-005-12', raceId: 'race-005', number: 12,
    name: 'Eclair du Soir', jockey: 'Sylvain Mula', trainer: 'Bruno Goop',
    owner: 'Haras du Soir', age: 6, weight: 0,
    odds: 16.0, oddsChange: 'down',
    recentForm: [
      { position: 4, date: '2026-04-16', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 3, date: '2026-03-30', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 2, date: '2026-03-13', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 5, date: '2026-02-24', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 3, date: '2026-02-07', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
    ],
    formRating: 'bon', careerWins: 11, careerRaces: 32, winRate: 34.4,
    earnings: 188000, preferredDistanceMin: 2600, preferredDistanceMax: 2800,
    preferredConditions: ['bon'],
    similarTrackWins: 6, similarTrackRaces: 14,
    aiScore: 60, winProbability: 8.8, confidenceLevel: 'moyen', isRecommended: false,
  },
  {
    id: 'h-005-13', raceId: 'race-005', number: 13,
    name: 'Greenshield', jockey: 'Philippe Allaire', trainer: 'Olivier Allaire',
    owner: 'Allaire Racing', age: 7, weight: 0,
    odds: 40.0, oddsChange: 'up',
    recentForm: [
      { position: 11, date: '2026-04-14', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 10, date: '2026-03-27', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 9, date: '2026-03-10', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
      { position: 7, date: '2026-02-22', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 8, date: '2026-02-05', racecourse: 'Le Mans', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
    ],
    formRating: 'mauvais', careerWins: 2, careerRaces: 30, winRate: 6.7,
    earnings: 18000, preferredDistanceMin: 2500, preferredDistanceMax: 3000,
    preferredConditions: ['bon'],
    similarTrackWins: 0, similarTrackRaces: 12,
    aiScore: 12, winProbability: 0.8, confidenceLevel: 'faible', isRecommended: false,
  },
  {
    id: 'h-005-14', raceId: 'race-005', number: 14,
    name: 'Davidson du Pont', jockey: 'Clément Lannois', trainer: 'Dominique Belhomme',
    owner: 'Haras du Pont', age: 5, weight: 0,
    odds: 25.0, oddsChange: 'down',
    recentForm: [
      { position: 5, date: '2026-04-12', racecourse: 'Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 14 },
      { position: 4, date: '2026-03-26', racecourse: 'Paris-Vincennes', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 13 },
      { position: 3, date: '2026-03-09', racecourse: 'Enghien', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 12 },
      { position: 1, date: '2026-02-21', racecourse: 'Caen', distance: 2700, trackCondition: 'bon', raceType: 'trot', opponents: 11 },
      { position: 4, date: '2026-02-04', racecourse: 'Vincennes', distance: 2700, trackCondition: 'léger', raceType: 'trot', opponents: 14 },
    ],
    formRating: 'bon', careerWins: 8, careerRaces: 24, winRate: 33.3,
    earnings: 130000, preferredDistanceMin: 2600, preferredDistanceMax: 2800,
    preferredConditions: ['bon', 'léger'],
    similarTrackWins: 4, similarTrackRaces: 10,
    aiScore: 52, winProbability: 6.2, confidenceLevel: 'faible', isRecommended: false,
  },
]

// Retourne les chevaux pour une course donnée
// À remplacer par: supabase.from('horses').select('*').eq('race_id', raceId)
export function getHorsesByRaceId(raceId: string): Horse[] {
  return MOCK_HORSES.filter(h => h.raceId === raceId)
}
